apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: slow-gce
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
